### ISSUE TITLE
Paridad de funcionalidad: Horario Maker

### ISSUE THREAD

**Issue by agucova** [open-source-uc/ramos-uc#10]
No sé si esto es razonable como objetivo o siquiera si vale la pena, pero creo que sería interesante intentar llevar el actual planificador a paridad de funcionalidad con plataformas como [HorarioMaker](https://horariomaker.com/). Esto implica implementar:

- [ ] Consultas avanzadas en la BBDD según cupos disponibles
- [ ] Implementar un solver automatizado en base a requisitos complejos, y potencialmente también una función objetivo. Esto puede ser en el back-end (como la plataforma de Ignacia) o [front-end](https://www.npmjs.com/package/javascript-lp-solver), lo que reduciría la carga.
- [ ] Un front-end amigable con fuerte foco en la UX que muestre y permite explorar las distintas alternativas. Aquí creo que hay harta oportunidad de mejora frente a plataformas existentes.

¿Qué piensan? ¿Vale la pena?

**Comment by nico-mac** [comment]
Es una idea interesante, me parece que HorarioMaker esta inactiva a nivel de desarrollo.

Creo que es una funcionalidad que habría que ver con tiempo y pensando bien los casos de uso. Por ejemplo muchas veces para armar un horario se tiene varias opciones de ramos y no necesariamente variedad de secciones o profesores. 

Probablemente vale la pena hacerlo para el próximo semestre, hacerlo bien puede ser harto trabajo. Me gustaría conocer más opiniones.

**Comment by aurmeneta** [comment]
Hola! Tal como lo he estado hablando con @agucova, una buena idea sería migrar [HorarioUC](https://github.com/aurmeneta/HorarioUC) a RamosUC. Por el momento solo permite buscar siglas y añadirlas y con estas generar combinaciones de horarios. Tenía planeado mejorar el buscador, poder configurar el tope de módulos y detallar mejor los cupos disponibles. 

La migración debería ser relativamente fácil. Las BBDD tienen la información necesaria, solo faltaría transcribir mi código en una app de Django.
