### ISSUE TITLE
Expandir calificaciones

### ISSUE THREAD

**Issue by agucova** [open-source-uc/ramos-uc#14]
De la reunión que tuvimos entre la Consejería Superior y @nico-mac surgió que es necesario expandir las calificaciones para que incluyan además estos ejes:

- Adaptación a contexto online (1 a 5, mayor es mejor)
- Comunicación entre profesores y estudiantes (1 a 5, mayor es mejor)

Además creo que podemos aprovechar de limpiar un poco el enunciado de las dos preguntas actuales a:

- ¿Cuánto recomendarías tomar este ramo? (1 al 5, mayor es mejor)
- ¿Cuánta carga académica consideras que tuvo este ramo? (1 al 5, mayor es más carga)

**Comment by mc-cari** [comment]
Lo voy a realizar

**Comment by nico-mac** [comment]
Esperate @mc-cari , perdón por no avisar pero hay un branch califications que ya tiene casi todo esto listo. Esta a la espera de unos cambios menores de diseño para hacer el PR.

**Comment by mc-cari** [comment]
Ah dale, np
