### ISSUE TITLE
Link a buscacursos

### ISSUE THREAD

**Issue by agucova** [open-source-uc/ramos-uc#17]
Con tal de facilitar el uso de Buscacursos acompañando Ramos UC, podría ser útil que el Planificador genere links de horario de Buscacursos automáticamente, además promoviendo validar los datos de Ramos UC con la fuente oficial de la universidad. 

La formación de URLs para un horario de Buscacursos es relativamente simple:
```https://buscacursos.uc.cl/?cursos=IMT3130-1,IIC1103-2```

Es decir, se usa el argumento `?cursos=` y luego sigue una lista separada por comas de siglas incluyendo la sección.

**Comment by mc-cari** [comment]
Hola, esto va a ser un botón en la sección de planifica que redirija a buscacursos?

**Comment by nico-mac** [comment]
Si @mc-cari , aunque puede redirigir o copiar el link, pero eso es.

**Comment by mc-cari** [comment]
Vale, lo voy a intentar

**Comment by nico-mac** [comment]
Excelente
