### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by agucova** [open-source-uc/ramos-uc#19]
Creo que sería buena idea que contemplemos el hacer backups periódicos de la BBDD de PostgreSQL especialmente por las evaluaciones ahora en adelante. No sé si esto ya se hace @nico-mac

**Comment by nico-mac** [comment]
Actualmente no se hacen automáticos, esto se podría hacer con un cron job simple o no?

**Comment by agucova** [comment]
Si, es bien fácil. Dónde guardas las copias de seguridad?

Porque creo que sería buena idea tener copias fuera del servidor en si.

**Comment by nico-mac** [comment]
Hasta ahora en el servidor mismo y en mi pc
