### ISSUE TITLE
Agregar organización al footer

### ISSUE THREAD

**Issue by nico-mac** [open-source-uc/ramos-uc#22]
Actualmente el footer de la página dice:

> by Nico Mc. nmcintyre@uc.cl

Sería bueno darle crédito a la organización también y talvez cambiar el mail por uno institucional.

**Comment by benjavicente** [comment]
Creo que lo de reconocer autor + organización es algo que vamos a tener que ver en varios proyectos.

Me imagino que se podría tener un formato así:
> Creado por [autor]. [Código abierto] mantenido en (o por?) [OSUC] gracias a [contibuidores].

Entonces para este caso el contenido del footer podría ser algo como:
> Creado por [Nico Mc](https://github.com/nico-mac). [Código abierto](https://github.com/open-source-uc/ramos-uc) mantenido por [OSUC](https://osuc.dev/) gracias a [contibuidores](https://github.com/open-source-uc/ramos-uc/graphs/contributors).

No creo que sea necesario dejar el mail en el footer si los mails están en las páginas, se podría dejar en una página de contacto si realmente es necesario, También hay que darle crédito a la consejería superior dentro del mismo footer si se va a trabajar en conjunto.

**Comment by nico-mac** [comment]
Definir el formato general escapa un poco de este proyecto, y además establecer que siempre sea en el footer y con un formato rígido no creo que sea lo mejor, cada proyecto puede tener su propio óptimo.

Si me gusta la idea de definir un contenido mínimo que debe haber, como incluir el nombre del autor, el link al repositorio, a la organización (con nombre completo Open Source UC) y citar de alguna manera a los contribuidores.

Respecto al formato para este caso
> Creado por Nico Mc. [Código abierto] mantenido por [OSUC] gracias a [contribuidores].

Me gusta como se ve, aunque las palabras exactas son un tema de gusto.

**Comment by agucova** [comment]
Encuentro raro el formato porque me da a entender que Nico ya no mantiene el proyecto. Y por lo demás el "a contribuidores" es poco gramatical. (a los)

Podría ser:
> Proyecto creado por [Nico MC](https://github.com/nico-mac) y mantenido en [OSUC](https://osuc.dev/) junto con más [contribuidores](https://github.com/open-source-uc/ramos-uc/graphs/contributors). Bajo la [licencia MIT](https://github.com/open-source-uc/ramos-uc/blob/main/LICENSE).

**Comment by benjavicente** [comment]
Está mucho mejor. Se podría añadir el link al repo, mencionando que es de código abierto (no creo que con que diga _licencia MIT_ sea claro para la mayoría), aunque añadirlo puede quedar muy verboso.

**Comment by nico-mac** [comment]
Me gusta la idea de dejar el link al repositorio. Muchas veces se pone "Ver código en [GitHub](https://github.com/open-source-uc/ramos-uc)" o algo similar y  no suena extrañamente verboso.
Creo que es mucho más útil un link al repo que a la licencia, porque además la licencia esta en el repo y es más del código que de la página como tal.

Mi favorito iría por:
> by Nico Mc. Mantenido con la ayuda de [contribuidores](https://github.com/open-source-uc/ramos-uc/graphs/contributors) <en/con el apoyo de> [OSUC](https://osuc.dev/).
> Ver en [GitHub](https://github.com/open-source-uc/ramos-uc)

Aunque si no hubiera problemas diría que poner *OpenSourceUC* es mucho más valioso que *OSUC*.

**Comment by agucova** [comment]
Te gusta estilizarlo con minúscula? 😳

**Comment by nico-mac** [comment]
Jeje, solo por que es *by*, si fuera *Creado por* lo pondría capitalizado de todas maneras.

**Comment by nico-mac** [comment]
@benjavicente @agucova para cerrar esto luego, que dejamos?

El *by Nico Mc.* y *Ver en GitHub* los dejaría así pero el resto que opinan?

**Comment by benjavicente** [comment]
> Proyecto creado por Nico Mc
> Mantenido con la ayuda de contribuidores en OSUC
> Código abierto disponible bajo la licencia XXX

Donde esas 3 líneas se pueden dejar separadas con una barra.

No se ve raro en la página por ser un mensaje muy largo, en móvil puede ser, pero se podría arreglar para que quede cada línea separada con html+css.

**Comment by agucova** [comment]
Opino que es demasiado verboso. No me importa poner código abierto o el link de GitHub en vez de la licencia. No soy fan del by, pero no es para tanto, así que lo dejaría:
> by Nico Mc. Mantenido con la ayuda de contribuidores de Open Source eUC.
> Ver en [GitHub](https://github.com/open-source-uc/ramos-uc/)

**Comment by agucova** [comment]
Increíble nuestro nivel de [bikeshedding](https://en.wikipedia.org/wiki/Law_of_triviality) jajaja

**Comment by aenrione** [comment]
#30 💄
