### ISSUE TITLE
Licencia

### ISSUE THREAD

**Issue by agucova** [open-source-uc/ramos-uc#24]
Quisiera plantear la posibilidad de dejar la licencia MIT y cambiarnos a la licencia [GPLv3](https://choosealicense.com/licenses/gpl-3.0/), que asegure que derivados del software también sean código abierto y respeten [las libertades del usuario.](https://en.wikipedia.org/wiki/The_Free_Software_Definition)

La licencia MIT me parece bacán para librerías y otro código para el cual es razonable esperar que usuarios mejoren el código sin publicar sus modificaciones o hacer su derivado código abierto, pero en este caso creo que algo así sería activamente dañino a la comunidad. 

Planteo una situación, totalmente hipotética, en la que alguien tome el proyecto y todo su código, lo mejore incrementalmente y lo publique sin hacer el código abierto o siquiera dar atribución a Nico. Una buena licencia debería impedir eso, y argumentaría que ese es el espíritu del software libre.

**Comment by agucova** [comment]
Por si acaso, entiendo que no podemos hacer que las versiones antiguas usen una nueva licencia. Esto solo aplicaría a versiones futuras del software.

**Comment by benjavicente** [comment]
Yo recomendé al inicio la licencia MIT porque en la mayoría de los casos yo no veo la necesidad de prohibir que alguien cree _freeware_ u otro software derivado mejor que un proyecto, pero si se va a tratar de transformar esta plataforma a algo más oficial me sumo a la moción de cambiar la licencia.

----

> (...) siquiera dar atribución a Nico

Acabo de entender que [_"the Software"_](https://github.com/open-source-uc/ramos-uc/blob/1fad8676e6a79559ddd7b3acf0880d9150c9e832/LICENSE#L6) se refiere al software original y no los derribados, entonces la limitación de la licencia MIT es que debe estar la licencia junto al software original que se utiliza en el derivado, pero sin necesariamente atribuir al código original.

[INAL](https://www.urbandictionary.com/define.php?term=INAL), pero parece que al tener un aviso de copyright en Chile [es necesario mencionar el autor en la obra derivada](https://www.bcn.cl/leychile/navegar?idNorma=28933&idParte=8636851). Aunque igual creo que con una licencia menor permisiva quedaría más claro u obligatorio que hay que mencionar el autor.

**Comment by agucova** [comment]
El problema acá es que no solo permitimos freeware, incluso permitimos vender el software de forma propietaria sin ninguna responsabilidad asociada.

La licencia MIT corresponde a un pase libre de todas las restricciones que por defecto tiene un proyecto en virtud del copyright. El MIT es básicamente decir, "haz lo que quieras, incluyendo ponerle una nueva licencia al proyecto". Ahora, ni GPLv3 ni MIT demandan atribución, GPL simplemente es más insistente en otros mínimos (como dar el código fuente).

**Comment by nico-mac** [comment]
Forzar que todos los proyectos derivados tengan que ser de código abierto es una restircción muy fuerte.

Pensando en casos futuros, ve principalmente 2 perfiles que podrían querer usar este software o derivados:
1. Estudiantes entusiastas de la UC u otras universidades
2. Universidades a nivel institucional

Un uso institucional en muchos casos preferiría usar un software menos abierto y eso, en lo personal, no me genera ningún problema. En caso de entusiastas, no esperaría conflictos de intereses.

Si sería óptimo para mi usar una licencia que obligue a hacer algún tipo de alusión al proyecto original. No se si eso existe.

**Comment by nico-mac** [comment]
Entiendo que la licencia Apache 2.0 requiere atribución pública siendo igual de permisiva que la MIT en otros aspectos.
