### ISSUE TITLE
Sincronización Manual de información sobre ramo

### ISSUE THREAD

**Issue by aenrione** [open-source-uc/ramos-uc#27]
Por lo que tengo entendido actualmente, la información de los ramos se actualiza automaticamente cada 1 hora o algo asi, ¿Como se va a manejar esto para las tomas de ramos? Quiero decir que si el usuario está en un intervalo con los cupos desactualizados tendrá que optar por usar igualmente el buscacursos. 

Estaba pensando que se podría implementar un sistema de actualización manual, en donde un usuario registrado pueda hacer una request para que la información de aquel ramo sea actualice en tiempo real sin tener que hacer el update automático masivo.

**Comment by agucova** [comment]
Me parece una buena idea, aunque habría que si o si agregar rate limiting. Es fácil abusar de un botón como ese :grimacing:

**Comment by nico-mac** [comment]
Suena interesante, solo me preocupa que podría agregar una carga considerable al servidor.

Recuerdo que para el 2020-2 hice una pestaña para hacer seguimiento a algunos ramos, donde uno ponía una lista de ramos y podía ver los cupos actualizandose automáticamente cada 1 minuto, todo mediante javascript en el cliente. El problema que había con eso era que no es fácil hacer el request a buscacursos desde javascript por la política de CORS, que bloquea requests desde otras páginas.
