### ISSUE TITLE
Flake 8 GitHub Actions

### ISSUE THREAD

**Issue by aenrione** [open-source-uc/ramos-uc#28]
Hola, siendo un proyecto open-source y viendo que actualmente igual trabajan con el formato flake-8 de python, quizá puedan implementar un github actions que realice un chequeo en los pull request para así asegurar un formato ordenado y universal para los colaboradores o los que intenten aportar con codigo al proyecto! 😄

**Comment by agucova** [comment]
Esto ya está implementado! Todos los PR deben pasar el Action de "Lint and check project" que pasa una suite de flake8 y fuerza el uso de formato Black.

De hecho las instrucciones de desarrollo además piden el uso de pre-commit con tal de validar el formato tipo Black desde antes de los commits, autorreparándolos si es necesario.
