### ISSUE TITLE
Botones sin funcionalidad

### ISSUE THREAD

**Issue by aenrione** [open-source-uc/ramos-uc#29]
Hola nose si ya estaban conscientes, pero actualmente hay 2 botones en la parte de "Planifica" que no tienen la funcionalidad objetiva:

El primero es el boton de abrir un horario guardado, el cual te manda a la página de inicio:
![20210723_122509](https://user-images.githubusercontent.com/60358967/126813089-45ac046f-5495-4f3b-8c21-bcdf8ef6ddda.gif)

El segundo es el botón de "Editar Horario" cuando uno comparte un horario:
![20210723_122604](https://user-images.githubusercontent.com/60358967/126813199-854832f2-5914-45a7-a6f7-9af1482245ca.gif)

**Comment by nico-mac** [comment]
Oh!
Sospecho que se rompió cuando planifica dejó de ser la url root.
Voy a echarle un ojo más de cerca de todas maneras.
