### ISSUE TITLE
IDEA: intervalo de Google Charts 

### ISSUE THREAD

**Issue by aenrione** [open-source-uc/ramos-uc#35]
Actualmente los graficos de disponibilidad de cupos se ven asi:
![image](https://user-images.githubusercontent.com/60358967/126903305-33c843c8-f4e3-4595-913d-0874ff293db4.png)

(imagen de ramo La Biblia de Jesús en 2021-1)

Si bien la toma de ramos inicial fue entre el 22 y 23, se muestran días siguientes que no tienen tanta relevancia a la toma misma, sería bueno poder agregar una opción o cambiar el intervalo para que muestre los cupos de los días de la toma de ramo con más detalles sobre las horas, para que el usuario pueda revisar en que horario se fueron más rapido (i.e: ver en que banner generalmente se van más rapido los cupos).

**Comment by nico-mac** [comment]
Esto es algo con lo que estamos totalmente al debe, esta relacionado con la issue #4.

Sería genial cambiarlo si tu o alguien más se anima. No estoy seguro pero creo que Google Charts no tiene todas las configuraciones necesarias para introducir esos cambios y talvez sea necesario cambiar la librería (lo que no debiera ser complicado).

**Comment by nico-mac** [comment]
Lo doy por resuelto en #103 .
