### ISSUE TITLE
Ordenar y documentar funcionamiento de assets

### ISSUE THREAD

**Issue by benjavicente** [open-source-uc/ramos-uc#36]
Como compilar los assets no está documentado y el directorio de assets está algo desordenado.

Por ejemplo: 

- Hay archivos como `boostrap.min.css` y `multiple-select.min.css` que son archivos mitificados, donde el primero parece que no se usa y ambos son dependencias de `node`.
- Hay scripts que podrían simplificarse y ordenarse demasiado utilizando JavaScript moderno o utilizando más funciones, como en la [creación de objetos](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#new_notations_in_ecmascript_2015) en [`query_body` de `search.js`](https://github.com/open-source-uc/ramos-uc/blob/cd26e031c9944fce4dea70496fe9a2c8100d4734/front/assets/src/search.js#L32-L49) y en la única función de 97 líneas con ~4 funciones anónimas anidadas en [`quota.js`](https://github.com/open-source-uc/ramos-uc/blob/main/front/assets/src/quota.js).
- Al correr `webpack` se genera un directorio `dist` que no está completamente ignorado por git.
- Ver para que es cada archivo requiere buscar como se usan en `webpack.config.js` y los otros scripts.

Entonces, para mejorar el orden y facilitar la resolución de #4, #15, #20, #21 y #35 creo que es necesario:

- [x] **Documentar como generar (o como funcionan) los assets**
- [ ] Agilizar la generación de los assets
- [x] Crear un directorio de como `helpers` o `utils` y dejar ahí los scripts auxiliares (los que no están en `entry` de `webpack`)
- [x] Eliminar los archivos minificados que podrían importarse de una dependencia de `node`
- [x] Eliminar `dist` del repositorio e ignorarlo

Una vez visto eso, se podría además ver si:

- Hacer un refactor de algunas partes del código para hacer más ágil los cambios a futuro
- Dejar un linter o formatter como `eslint`
- Se elimina la dependencia de `jquery`
- Sobreescribir los colores principales de Boostrap en `base.css`

**Comment by nico-mac** [comment]
Toda la carpeta de assets es tan desastrosa como mi entendimiento sobre webpack, js moderno y css moderno.

Un buen punto de partida podría ser trasladar algunos archivos a un directorio `utils` (como dices, los que no son entries), eliminar los archivos que puedan importarse como dependencias, hacer documentación e incorporar un formatter.

Preferiría mantener la carpeta `dist` mientras que no esté automatizada la compilación de assets, para no complejizar más el setup y deploy por mientras.

**Comment by nico-mac** [comment]
Creo que todo esto ya esta listo. Si efectivamente no falta nada más, puedes cerrar la issue @benjavicente.

**Comment by benjavicente** [comment]
Faltó ver el tema de agilizar la generación de assets, idealmente se deberían generar al haber cambios cuando se corre el servidor al probarlo. Pero por lo que he visto, django no tiene una buena integración con webpack, entonces se podría dejar como algo bueno a tener en el futuro y no necesario.
 
Como se cumplió la meta de la issue, la cierro nomás.
