### ISSUE TITLE
Mejor visualización de cupos por hora

### ISSUE THREAD

**Issue by agucova** [open-source-uc/ramos-uc#4]
Cito desde una conversación de Whatsapp:
> (...) en la linea temporal de los cupos podrias añadir lineas verticales que indiquen que banner estaba tomando a tal hora
> si al final pa eso se ocupa

Podríamos efectivamente mejorar la visualización para que sobreponga los banners y sea mas fácil distinguir si tu banner alcanza o no a tomar el ramo.

**Comment by nico-mac** [comment]
Es parte del plan, eso si la implementación actual es con Google Charts y creo que no se puede hacer eso. Podría ser necesario cambiar de librería.

**Comment by EnzoMorata** [comment]
Para crear visualizaciones estáticas y dinámicas una muy buena librería de D3.js . Tal vez, pueda dedicar un tiempo a plantear cómo se podrían realizar mejoras a la visualización y cómo codificarlo mediante D3.

**Comment by agucova** [comment]
Estoy de acuerdo, y tampoco debiese ser un gráfico particularmente difícil de hacer.

**Comment by EnzoMorata** [comment]
Durante estos días voy a ver si puedo lograr hacer alguna propuesta de visualización mediante D3 para ver mejor los cupos. No utilizado Django antes, así que no sé cuanto pueda tardarme en poder implementar el código de la visualización para que funcione en conjunto con la aplicación.

**Comment by nico-mac** [comment]
Puede que no necesites alterar nada de Django, los gráficos se hacen dinamicamente en el front con javascript, con los datos de una consulta tipo API. En cualquier caso, sientete libre de cambiar lo que necesites!

**Comment by EnzoMorata** [comment]
Hola, quería compartir el [repositorio](https://github.com/EnzoMorata/RamosUC-visualization) en donde dejaré los avances que haga sobre la propuesta de visualización que vaya desarrollando, y así también poder ver los avances de la [Propuesta de Visualización](https://enzomorata.github.io/RamosUC-visualization/) mediante GitHub Pages.

**Comment by nico-mac** [comment]
Lo doy por resuelto en #103 .
