### ISSUE TITLE
getCookie no lee cookies correctamente

### ISSUE THREAD

**Issue by aurmeneta** [open-source-uc/ramos-uc#48]
La expresión regular para buscar una cookie no reconoce todas las cookies. Las cookies están guardadas en el formato `cookie=valor; cookie2=valor; cookie3=valor`. Notar que última cookie no tiene `;` al final. La expresión regular ignora este último término.

**Comment by agucova** [comment]
En qué contexto es esto?

**Comment by benjavicente** [comment]
Esto de aquí:

https://github.com/open-source-uc/ramos-uc/blob/002d2cb2f8623f99a2bdb43bdc7bc5ffb61bdf00/front/assets/src/utils/cookies.js#L11

Debería ser algo como:

```regexp
${cname}=(?<value>[^;]*?)(;|$)  # Hasta un ; o al final del string ($)
```
