### ISSUE TITLE
Error de redondeo en calificaciones

### ISSUE THREAD

**Issue by ivanvlam** [open-source-uc/ramos-uc#50]
Hay calificaciones de los cursos que no salen redondeadas a la décima y presentan muchos decimales, como es el caso de Ecuaciones Diferenciales MAT1640 en el semestre 2021-1. Se puede ver en https://ramosuc.cl/ramo/MAT1640?period=2021-1.

**Comment by nico-mac** [comment]
Esto fue mencionado en #40 y solucionado en #47, todavía no se hace la actualización en el servidor. Probablemente lo suba hoy durante la noche.
Muchas gracias por avisar de todas maneras.
