### ISSUE TITLE
[Crea] Posibilidad de filtrar por sección

### ISSUE THREAD

**Issue by ggmirandac** [open-source-uc/ramos-uc#56]
Hola, en la nueva sección de crear, seria bueno poder filtrar por sección, de forma de poder sacar de las combinaciones aquellas secciones que no so útiles en el horario que se esta confeccionando.

**Comment by aurmeneta** [comment]
Tengo pensado agregar un modal donde el usuario pueda ver un resumen de las secciones del ramo y elegir con cuales quiere generar las combinaciones. A diferencia de lo que originalmente estaba en HorarioUC, se permitiría elegir varias secciones.
