### ISSUE TITLE
Error con programa de curso ING1024 e ING1004

### ISSUE THREAD

**Issue by lnatero** [open-source-uc/ramos-uc#78]
## Error de sección: Programa
El ramo [ING1024](https://ramosuc.cl/ramo/ING1024) en la sección de **Programa** muestra el programa de desafíos de la ingeniería ([ING1004](https://ramosuc.cl/ramo/ING1004)), y en la sección de **Programa** de desafíos de la ingeniería aparece "Programa de curso no disponible".

### ING1024
![image](https://user-images.githubusercontent.com/64765306/147950257-5ae400b1-a8d4-4e18-8e3a-b4c60ce3726f.png)

### ING1004
![image](https://user-images.githubusercontent.com/64765306/147950480-973d9cac-a7f6-4ec1-8bd8-3cb0e554d681.png)

**Comment by nico-mac** [comment]
Está malo en el [catalogo UC](https://catalogo.uc.cl/), no hay nada que podamos hacer desde nuestro lado salvo dar aviso.
