### ISSUE TITLE
Ramos híbridos y con actividades

### ISSUE THREAD

**Issue by agucova** [open-source-uc/ramos-uc#9]
Probablemente la funcionalidad más importante en vista del próximo semestre va a ser poder fácilmente etiquetar ramos híbridos y con actividades. Se espera que a partir del próximo semestre, alrededor de 30% de los ramos de la universidad tengan modalidad híbrida, y muchas personas van a estar buscando esos ramos exclusivamente.

**Funcionalidad clave a tener**
- [x] Datos sobre la modalidad de cada curso en DB (`HIB`, `REPR`, `PR`, `OL`)
- [ ] Una visualización clara y fácil de encontrar que muestre la modalidad de cada curso.
- [x] Un filtro de búsqueda para ramos híbridos y con actividades presenciales.

No estoy del todo seguro cuáles de estos ya están listos. Noté que hay un atributo `formato` en BBDD, pero no lo pude encontrar en la interfaz.

**Comment by nico-mac** [comment]
En la DB esta el formato de todos los ramos, especificado a nivel de sección.  
En la página de planificación, dentro de los filtros está el de formato y se pueden especificar varios a la vez.  
El formato se muestra al hacer click en el botón que contiene la sigla de la sección en la tabla de resultados de la planificación y también al ver las secciones en la página específica de cada curso.

Creo que para aumentar la visibildad del formato debiera incluirse directamente como columna de la tabla de resultados, y además se podría cambiar la posición del filtro o destacarlo de alguna manera.

**Comment by nico-mac** [comment]
![image](https://user-images.githubusercontent.com/16323007/126718818-3a627b53-06a6-46b3-947e-6612321c7e98.png)
![image](https://user-images.githubusercontent.com/16323007/126719000-a61e14a0-0f1f-4741-852c-e48fadadf413.png)

¿Con fondo, con borde o sin nada?
Se aceptan otras alternativas también.

**Comment by agucova** [comment]
Uhhh, interesante.

Yo creo que sin. Está bien que sea llamativo pero tal vez no tanto.
